version: '3.8'
services:
  db:
    image: "postgres:13.3"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "flaskapp_db"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    ports:
      - 5432:5432
  flaskapp:
    build: .
    volumes:
      - .:/opt/services/flaskapp/src
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "flaskapp_db"
      APP_SECRET_KEY: "ateliware"
    ports:
      - 5000:5000
    depends_on:
      - db
volumes:
  dbdata:
